import React from 'react';
import { AbsoluteFill } from 'remotion';
import { AspectRatio } from '../../config/videoConfig';

interface BrandedFrameProps {
  children: React.ReactNode;
  aspectRatio: AspectRatio;
  theme?: 'light' | 'dark' | 'gradient';
  brandColor?: string;
  showLogo?: boolean;
  showWatermark?: boolean;
  className?: string;
}

export const BrandedFrame: React.FC<BrandedFrameProps> = ({
  children,
  aspectRatio,
  theme = 'light',
  brandColor = '#3b82f6',
  showLogo = false,
  showWatermark = true,
  className = ''
}) => {
  const getThemeStyles = () => {
    switch (theme) {
      case 'dark':
        return {
          background: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)',
          color: '#f9fafb',
        };
      case 'gradient':
        return {
          background: `linear-gradient(135deg, ${brandColor} 0%, ${adjustBrightness(brandColor, -20)} 100%)`,
          color: '#ffffff',
        };
      default:
        return {
          background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
          color: '#1f2937',
        };
    }
  };
  
  const adjustBrightness = (color: string, percent: number) => {
    // Simple color adjustment - in a real app, you'd use a proper color library
    const num = parseInt(color.replace('#', ''), 16);
    const amt = Math.round(2.55 * percent);
    const R = (num >> 16) + amt;
    const G = (num >> 8 & 0x00FF) + amt;
    const B = (num & 0x0000FF) + amt;
    return '#' + (0x1000000 + (R < 255 ? R < 1 ? 0 : R : 255) * 0x10000 +
      (G < 255 ? G < 1 ? 0 : G : 255) * 0x100 +
      (B < 255 ? B < 1 ? 0 : B : 255)).toString(16).slice(1);
  };
  
  const getPadding = () => {
    switch (aspectRatio) {
      case '9:16':
        return '20px';
      case '1:1':
        return '30px';
      default:
        return '40px';
    }
  };
  
  return (
    <AbsoluteFill
      className={className}
      style={{
        ...getThemeStyles(),
        padding: getPadding(),
        fontFamily: 'Inter, system-ui, sans-serif',
      }}
    >
      {/* Brand accent border */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height: '4px',
          background: brandColor,
        }}
      />
      
      {/* Logo */}
      {showLogo && (
        <div
          style={{
            position: 'absolute',
            top: getPadding(),
            left: getPadding(),
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            zIndex: 10,
          }}
        >
          <div
            style={{
              width: '24px',
              height: '24px',
              borderRadius: '4px',
              background: brandColor,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white',
              fontSize: '12px',
              fontWeight: 'bold',
            }}
          >
            AI
          </div>
          <span
            style={{
              fontSize: '14px',
              fontWeight: '600',
              opacity: 0.8,
            }}
          >
            Video Creator
          </span>
        </div>
      )}
      
      {/* Main content */}
      <div
        style={{
          position: 'relative',
          width: '100%',
          height: '100%',
          zIndex: 1,
        }}
      >
        {children}
      </div>
      
      {/* Watermark */}
      {showWatermark && (
        <div
          style={{
            position: 'absolute',
            bottom: getPadding(),
            right: getPadding(),
            fontSize: '10px',
            opacity: 0.4,
            fontWeight: '500',
          }}
        >
          Generated by AI
        </div>
      )}
    </AbsoluteFill>
  );
};